FROM python:3.10 as base

FROM base as builder

RUN mkdir /install
# RUN apk update && apk add postgresql-dev gcc python3-dev musl-dev
WORKDIR /install
COPY etl/requirements_win.txt /requirements.txt
RUN pip install --upgrade pip \
    && pip install --prefix=/install -r /requirements.txt

FROM base

COPY --from=builder /install /usr/local
# RUN apk --no-cache add libpq

WORKDIR /opt/app
COPY docker/wait-for-it.sh wait-for-it.sh
COPY config/windows/lib_lsl_win /usr/local/lib/python3.10/site-packages/pylsl/lib
COPY config /opt/app/config
COPY etl .

RUN sed -i 's/\r$//g' /opt/app/wait-for-it.sh \
    && chmod +x  /opt/app/wait-for-it.sh

#EXPOSE 8000
