# Используем официальный образ Windows с установленным Python
FROM mcr.microsoft.com/windows/servercore:ltsc2019

# Устанавливаем рабочую директорию
WORKDIR C:\app

# Устанавливаем Python 3.10
RUN powershell -Command " \
    [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12; \
    Invoke-WebRequest -Uri 'https://www.python.org/ftp/python/3.10.0/python-3.10.0-amd64.exe' -OutFile 'python-installer.exe'; \
    Start-Process -FilePath 'python-installer.exe' -ArgumentList '/quiet InstallAllUsers=1 PrependPath=1' -Wait; \
    Remove-Item -Force 'python-installer.exe' \
"

# Обновляем pip
RUN python -m pip install --upgrade pip

# Копируем файлы requirements.txt и устанавливаем зависимости
COPY .\app\requirements.txt C:\app\requirements.txt
RUN pip install --no-cache-dir -r C:\app\requirements.txt && \
    pip install pydantic[email] rethinkdb sqlalchemy_utils sqlalchemy looseversion

# Копируем код приложения
COPY .\app C:\app

# Открываем порт 8001
EXPOSE 8001

# Устанавливаем переменные окружения (если необходимо)
ENV PYTHONUNBUFFERED=1

# Команда для запуска приложения
CMD ["python", "-m", "uvicorn", "main:app", "--host", "0.0.0.0", "--port=8001"]
