# Используем официальный образ Python
FROM python:3.10-alpine

# Устанавливаем рабочую директорию
WORKDIR /app

# Установка переменной окружения PYTHONPATH
ENV PYTHONPATH="/app"

# Копируем файлы requirements.txt и устанавливаем зависимости
COPY ./app/requirements.txt /app/requirements.txt

# Установка pytest и других необходимых инструментов
RUN pip install --no-cache-dir -r /app/requirements.txt \
    && pip install pytest pydantic[email] rethinkdb

# Копируем все содержимое папки приложения и тестов в контейнер
COPY ./app /app
COPY ./tests /tests

# Устанавливаем переменные окружения (если необходимо)
ENV PYTHONUNBUFFERED 1

# Устанавливаем рабочую директорию для запуска тестов
WORKDIR /tests

# Создание всех необходимых директорий и файлов логов при запуске контейнера
ENTRYPOINT ["/bin/sh", "-c", "mkdir -p /tests/logs && \
    touch /tests/logs/app_admin_panel.log && \
    touch /tests/logs/interface.log && \
    touch /tests/logs/main.log && \
    touch /tests/logs/filtration_manager.log && \
    touch /tests/logs/manager_settings.log && \
    touch /tests/logs/processing_manager.log && \
    touch /tests/logs/load_data.log && \
    touch /tests/logs/processes_control.log && \
    pytest -p no:warnings -v ."]
