FROM python:3.10 as base

FROM base as builder

RUN mkdir /install
WORKDIR /install
COPY etl/requirements_linux.txt /requirements.txt
RUN pip install --upgrade pip \
    && pip install --prefix=/install -r /requirements.txt

FROM base

COPY --from=builder /install /usr/local

WORKDIR /opt/app
COPY docker/run_test_stream.sh run_test_stream.sh
COPY config/linux/lib_lsl_linux /usr/local/lib/python3.10/site-packages/pylsl/lib
COPY config /opt/app/config
COPY etl .

RUN sed -i 's/\r$//g' /opt/app/run_test_stream.sh \
    && chmod +x  /opt/app/run_test_stream.sh

#EXPOSE 8000
